compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: highsierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: null
      fc: null
    spec: clang@9.1.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {
      cxxflags: "-stdlib=libc++"
    }
    modules: []
    operating_system: highsierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: null
      fc: null
    spec: clang@10.0.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu16.04
    paths:
      cc: /usr/lib/llvm-5.0/bin/clang
      cxx: /usr/lib/llvm-5.0/bin/clang++
      f77: /usr/bin/gfortran-4.9
      fc: /usr/bin/gfortran-4.9
    spec: clang@5.0.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {
      cxxflags: "-stdlib=libc++"
    }
    modules: []
    operating_system: ubuntu16.04
    paths:
      cc: /usr/bin/clang-6.0
      cxx: /usr/bin/clang++-6.0
      f77: null
      fc: null
    spec: clang@6.0.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu16.04
    paths:
      cc: /usr/local/clang-7.0.0/bin/clang
      cxx: /usr/local/clang-7.0.0/bin/clang++
      f77: /usr/bin/gfortran-4.9
      fc: /usr/bin/gfortran-4.9
    spec: clang@7.0.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14.04
    paths:
      cc: /usr/bin/gcc-4.8
      cxx: /usr/bin/g++-4.8
      f77: /usr/bin/gfortran-4.8
      fc: /usr/bin/gfortran-4.8
    spec: gcc@4.8.5
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14.04
    paths:
      cc: /usr/bin/gcc-4.9
      cxx: /usr/bin/g++-4.9
      f77: /usr/bin/gfortran-4.9
      fc: /usr/bin/gfortran-4.9
    spec: gcc@4.9.4
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14.04
    paths:
      cc: /usr/bin/gcc-6
      cxx: /usr/bin/g++-6
      f77: /usr/bin/gfortran-6
      fc: /usr/bin/gfortran-6
    spec: gcc@6.5.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14.04
    paths:
      cc: /usr/bin/gcc-7
      cxx: /usr/bin/g++-7
      f77: /usr/bin/gfortran-7
      fc: /usr/bin/gfortran-7
    spec: gcc@7.4.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu16.04
    paths:
      cc: /usr/bin/gcc-8
      cxx: /usr/bin/g++-8
      f77: /usr/bin/gfortran-8
      fc: /usr/bin/gfortran-8
    spec: gcc@8.1.0
    target: x86_64
