name: source

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Non-ASCII Characters
      run: .github/workflows/source/hasNonASCII
    - name: TABs
      run: .github/workflows/source/hasTabs
    - name: End-of-Line whitespaces
      run: .github/workflows/source/hasEOLwhiteSpace
    - name: PEP8
      run: |
        python3 -m pip install -U flake8
        python3 -m flake8 --exclude=thirdParty .

  static-analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: pyflakes
      run: |
        python3 -m pip install -U pyflakes
        python3 -m pyflakes docs/ examples/ test/ setup.py

  documentation:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1.0.5
      with:
        update-conda: true
        conda-channels: conda-forge
    - name: Install
      run: conda install -c conda-forge doxygen
    - name: Doxygen
      run: .github/workflows/source/buildDoxygen
